logging:
  file:
    name: ./logs/csgo-round-parser.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        csgoutil:
          roundparser: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demfiles
    username: ${POSTGRES_USER:REPLACE_ME} # Replace the value
    password: ${POSTGRES_PASSW:REPLACE_ME} # Replace the value
  mail:
    host: smtp.gmail.com
    port: 587
    username: XXXX
    password: XXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /demparser
com:
  marco:
    csgoutil:
      notification:
        enabled: false
        emailrecipients: marcosolina@gmail.com # A list of comma separated email addresses
      roundparser:
        version: ^project.version^
        environment: WINDOWS # Enum: WINDOWS, RASP
        executionType: SYNC # Enum: ASYNC, SYNC
        demfolder: "C:\\tmp\\demfiles"
        dotnetexecutable: "E:\\Workspaces\\Git\\csgo_util\\DemParser\\bin\\Debug\\netcoreapp3.1\\DemParser.dll"
        deleteBadDemFiles: false