server:
  servlet:
    context-path: /rcon
  port: 8081
    
csgorestapi:
  version: ^project.version^
  notification:
    telegram:
      enabled: true
      telegramToken: TELEGRAM_TOKEN
      chatGroupId: TELGRAM_GROUP_ID


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/csgorcon
    username: ${POSTGRES_USER:REPLACE_ME} # Replace the value
    password: ${POSTGRES_PASSW:REPLACE_ME} # Replace the value

logging:
  file:
    name: ./logs/csgo-rcon-status.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        csgorestapi: DEBUG