server:
  servlet:
    context-path: /rcon
    
csgorestapi:
  version: ^project.version^
    
logging:
  file:
    name: ./logs/csgo-rcon-status.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        csgorestapi: DEBUG