version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  demmanager:
    image: ixigo_dem_manager
    environment:
      IXIGO_CONFIG_SERVER_USER: __IXIGO_CONFIG_SERVER_USER__
      IXIGO_CONFIG_SERVER_PASSW: __IXIGO_CONFIG_SERVER_PASSW__
      IXIGO_POSTGRES_PASSW: __IXIGO_POSTGRES_PASSW__
      IXIGO_POSTGRES_USER: __IXIGO_POSTGRES_USER__
    networks: 
      - ixigo
    build:
      context: ./IxigoDemManager
    ports:
      - "8081:8081"
    depends_on: 
      - dbpostgres
  configService:
    image: ixigo_config
    environment:
      IXIGO_CONFIG_REPO: "https://github.com/marcosolina/csgo_util.git"
      IXIGO_CONFIG_SERVER_USER: __IXIGO_CONFIG_SERVER_USER__
      IXIGO_CONFIG_SERVER_PASSW: __IXIGO_CONFIG_SERVER_PASSW__
      IXIGO_GIT_REPO_BRANCH: refactoring
      IXIGO_CONFIG_ENC_KEY: __IXIGO_CONFIG_ENC_KEY__
    networks: 
      - ixigo
    build:
      context: ./IxigoConfigServer
    ports:
      - "8888:8888"
  discoveryService:
    image: ixigo_discovery
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscovery
    ports:
      - "8765:8765"
  dbpostgres:
    image: postgres_ixigo
    environment:
      POSTGRES_PASSWORD: __IXIGO_POSTGRES_PASSW__
      POSTGRES_USER: __IXIGO_POSTGRES_USER__
    networks: 
      - ixigo
    build:
      context: ./PostgreSql
    ports:
      - "5432:5432"