version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  demmanager:
    image: ixigo_dem_manager
    env_file:
      - ./decker-compose-env-file.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDemManager
    ports:
      - "8081:8081"
    depends_on: 
      - dbpostgres
  configService:
    image: ixigo_config
    env_file:
      - ./decker-compose-env-file.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoConfigServer
    ports:
      - "8888:8888"
  discoveryService:
    image: ixigo_discovery
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscovery
    ports:
      - "8765:8765"
  dbpostgres:
    image: postgres_ixigo
    env_file:
      - ./decker-compose-env-file.properties
    networks: 
      - ixigo
    build:
      context: ./PostgreSql
    ports:
      - "5432:5432"