version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  csgo:
    image: ixigo_csgo
    env_file:
      - ./env-spring-config.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
      - ./env-csgo-server.properties
    networks: 
      - ixigo
    build:
      context: ./CsGoServer
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
      - "27005:27005/udp"
      - "51840:51840/udp"
    volumes: 
      - "__CSGO_FOLDER__:/csgoserver/ixi_go"
    depends_on: 
      - my_maven
  my_maven:
    image: my_maven
    networks: 
      - ixigo
    build:
      context: ./Build
  dbpostgres:
    image: postgres_ixigo
    env_file:
      - ./env-database.properties
    networks: 
      - ixigo
    build:
      context: ./PostgreSql
    ports:
      - "5432:5432"
  