version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  demmanager:
    image: ixigo_dem_manager
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDemManager
    ports:
      - "8081:8081"
    depends_on: 
      - dbpostgres
    volumes: 
      - "/home/marco/Windows/test:/demFiles"
  config-service:
    image: ixigo_config
    env_file:
      - ./env-spring-config.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoConfigServer
    ports:
      - "8888:8888"
  discovery-service:
    image: ixigo_discovery
    env_file:
      - ./env-eureka.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscovery
    ports:
      - "8765:8765"
  dbpostgres:
    image: postgres_ixigo
    env_file:
      - ./env-database.properties
    networks: 
      - ixigo
    build:
      context: ./PostgreSql
    ports:
      - "5432:5432"