version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  demmanager:
    image: ixigo_dem_manager
    environment:
      IXIGO_CONFIG_SERVER_USER: ${IXIGO_CONFIG_SERVER_USER}
      IXIGO_CONFIG_SERVER_PASSW: ${IXIGO_CONFIG_SERVER_PASSW}
      IXIGO_POSTGRES_PASSW: ${IXIGO_POSTGRES_PASSW}
      IXIGO_POSTGRES_USER: ${IXIGO_POSTGRES_USER}
    networks: 
      - ixigo
    build:
      context: ./IxigoDemManager
    ports:
      - "8081:8081"
    depends_on: 
      - dbpostgres
  configService:
    image: ixigo_config
    environment:
      IXIGO_CONFIG_REPO: "https://github.com/marcosolina/csgo_util.git"
      IXIGO_CONFIG_SERVER_USER: ${IXIGO_CONFIG_SERVER_USER}
      IXIGO_CONFIG_SERVER_PASSW: ${IXIGO_CONFIG_SERVER_PASSW}
      IXIGO_GIT_REPO_BRANCH: main
      IXIGO_CONFIG_ENC_KEY: ${IXIGO_CONFIG_ENC_KEY}
    networks: 
      - ixigo
    build:
      context: ./IxigoConfigServer
    ports:
      - "8888:8888"
  discoveryService:
    image: ixigo_discovery
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscovery
    ports:
      - "8765:8765"
    depends_on:
  dbpostgres:
    image: postgres_ixigo
    environment:
      POSTGRES_PASSWORD: ${IXIGO_POSTGRES_PASSW}
      POSTGRES_USER: ${IXIGO_POSTGRES_USER}
      
    networks: 
      - ixigo
    build:
      context: ./PostgreSql
    ports:
      - "5432:5432"