version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  my_maven:
    image: my_maven
    networks: 
      - ixigo
    build:
      context: ./Build
  discord-bot:
    image: ixigo_discord_bot
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscordBot
    ports:
      - "8082:8082"
    depends_on: 
      - dbpostgres
      - my_maven
  dem-manager:
    image: ixigo_dem_manager
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDemManager
    ports:
      - "8081:8081"
    depends_on: 
      - dbpostgres
      - my_maven
    volumes: 
      - "__DEM_FOLDER__:/demFiles"
  config-service:
    image: ixigo_config
    env_file:
      - ./env-spring-config.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoConfigServer
    ports:
      - "8888:8888"
    depends_on:
      - my_maven
  discovery-service:
    image: ixigo_discovery
    env_file:
      - ./env-eureka.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscovery
    ports:
      - "8765:8765"
    depends_on:
      - my_maven
  dbpostgres:
    image: postgres_ixigo
    env_file:
      - ./env-database.properties
    networks: 
      - ixigo
    build:
      context: ./PostgreSql
    ports:
      - "5432:5432"