version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  csgo:
    image: ixigo_csgo
    env_file:
      - ./env-spring-config.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
      - ./env-csgo-server.properties
    networks: 
      - ixigo
    build:
      context: ./CsGoServer
    ports:
      - "27000-28000"
    volumes: 
      - "__CSGO_FOLDER__:/csgoserver/ixi_go"
    depends_on: 
      - my_maven
  my_maven:
    image: my_maven
    networks: 
      - ixigo
    build:
      context: ./Build
  discord-bot:
    image: ixigo_discord_bot
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscordBot
    ports:
      - "8082:8082"
    depends_on: 
      - dbpostgres
      - my_maven
  players-manager:
    image: ixigo_players_manager
    env_file:
      - ./env-spring-config.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoPlayersManager
    ports:
      - "8087:8087"
    depends_on: 
      - my_maven
  event-dispatcher:
    image: ixigo_event_dispatcher
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoEventDispatcher
    ports:
      - "8086:8086"
    depends_on: 
      - dbpostgres
      - my_maven
  dem-manager:
    image: ixigo_dem_manager
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDemManager
    ports:
      - "8081:8081"
    depends_on: 
      - dbpostgres
      - my_maven
    volumes: 
      - "__DEM_FOLDER__:/demFiles"
  config-service:
    image: ixigo_config
    env_file:
      - ./env-spring-config.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoConfigServer
    ports:
      - "8888:8888"
    depends_on:
      - my_maven
  discovery-service:
    image: ixigo_discovery
    env_file:
      - ./env-eureka.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscovery
    ports:
      - "8765:8765"
    depends_on:
      - my_maven
  dbpostgres:
    image: postgres_ixigo
    env_file:
      - ./env-database.properties
    networks: 
      - ixigo
    build:
      context: ./PostgreSql
    ports:
      - "5432:5432"
  ixigo-proxy:
    image: ixigo_proxy
    env_file:
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoProxy
    ports:
      - "8763:8763"
    depends_on: 
      - my_maven
  rcon-api:
    image: rcon_api
    env_file:
      - ./env-eureka.properties
      - ./env-spring-common.properties
      - ./env-spring-config.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoRconApiService
    ports:
      - "8084:8084"
    depends_on: 
      - my_maven
  ixigo-ui:
    image: ixigo_ui
    env_file:
      - ./env-eureka.properties
      - ./env-spring-common.properties
      - ./env-spring-config.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoUi
    ports:
      - "8089:8089"
    depends_on: 
      - my_maven