version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  demmanager:
    image: ixigo_dem_manager
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDemManager
    ports:
      - "8081:8081"
    depends_on: 
      - dbpostgres
    volumes: 
      - "/home/marco/Windows/test:/demFiles"