version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  csgo:
    image: ixigo_csgo
    env_file:
      - ./env-spring-config.properties
      - ./env-database.properties
      - ./env-eureka.properties
      - ./env-spring-common.properties
    networks: 
      - ixigo
    build:
      context: ./CsGoServer
    ports:
      - "27000-28000"
    volumes: 
      - "/home/marco/Windows/test/csgoproject:/csgoserver/ixi_go"