version: "3.7"

networks:
  ixigo:
    name: ixigo_network

services:
  discovery-service:
    image: ixigo_discovery
    env_file:
      - ./env-eureka.properties
    networks: 
      - ixigo
    build:
      context: ./IxigoDiscovery
    ports:
      - "8765:8765"