logging:
  file:
    name: ./logs/discordbot.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        ixigoserverhelper: DEBUG

server:
  servlet:
    context-path: /ixigohelper
  port: 8083
  
ixigohelper:
  version: ^project.version^
  demfilesserice: 
    demFilesFolderFullPath: "C:\\tmp\\demfiles"
    parserservice:
      protocol: "https"
      host: "marco.selfip.net"
      commonPath: "/zuul/csgo-round-parser-api/demparser"
      endpoint: "${ixigohelper.demfilesserice.parserservice.commonPath}/newdata"
      demFilesUploaEndpoint: "${ixigohelper.demfilesserice.parserservice.commonPath}/files"
  rconservice:
      protocol: "https"
      host: marco.selfip.net
      commonPath: "/zuul/csgo-rest-api/rcon"
      eventEndpoint: "${ixigohelper.rconservice.commonPath}/event"
      sendEvents: false
    
