logging:
  file:
    name: ./logs/server-helper.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
       ixigo:
         serverhelper: DEBUG

server:
  servlet:
    context-path: /ixigohelper
  port: 8083
  
com:
  marco:
   ixigo:
     serverhelper:
       version: ^project.version^
       demFilesFolderFullPath: "E:\\VmSharedFiles\\CsgoServer\\ixi_go\\CsgoServer\\csgo"
       justmondaynight: true
       services:
         demmanager:
           protocol: http
           host: 192.168.1.25
           port: 8763
           contextPath: "/ixigoproxy/ixigo-dem-manager/demmanager"
           uploadFile: "${com.marco.ixigo.serverhelper.services.demmanager.commonPath}/files"
           parseFile: "${com.marco.ixigo.serverhelper.services.demmanager.commonPath}/parse"
         eventdispatcher:
           protocol: http
           host: 192.168.1.25
           port: 8763
           contextPath: "/demmanager"
           dispatchEvent: "${com.marco.ixigo.serverhelper.services.eventDispatcher.commonPath}/event"
           sendEvents: false
