logging:
  file:
    name: ./logs/server-helper.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
       ixigo:
         serverhelper: DEBUG

server:
  servlet:
    context-path: /ixigohelper
  port: 8083
  
com:
  marco:
   ixigo:
     serverhelper:
       version: ^project.version^
       demFilesFolderFullPath: "C:\\tmp\\demfiles"
       services:
         demmanager:
           protocol: http
           host: localhost
           port: 8080
           contextPath: "/demmanager"
           uploadFile: "${com.marco.ixigo.serverhelper.services.demmanager.commonPath}/files"
           parseFile: "${com.marco.ixigo.serverhelper.services.demmanager.commonPath}/parse"
         eventDispatcher:
           protocol: http
           host: localhost
           port: 8080
           contextPath: "/demmanager"
           dispatchEvent: "${com.marco.ixigo.serverhelper.services.eventDispatcher.commonPath}"
           sendEvents: false
