logging:
  file:
    name: ./logs/discordbot.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        ixigoserverhelper: DEBUG

server:
  servlet:
    context-path: /ixigohelper
  port: 8083
  
ixigohelper:
  version: ^project.version^
  demfilesserice: 
    demFilesFolderFullPath: "E:\\VmSharedFiles\\CsgoServer\\ixi_go\\CsgoServer\\csgo"
    
