logging:
  file:
    name: ./logs/server-helper.log
  level:
    com:
      ixigo:
        serverhelper: DEBUG

server:
  servlet:
    context-path: /ixigohelper                                                                                    # Do not change this

com:
  ixigo:
    serverhelper:
      version: ^project.version^
      dem-files:
        dem-files-folder-full-path: "E:\\VmSharedFiles\\CsgoServer\\ixi_go\\CsgoServer\\csgo" # Full path the the csgo game server folder
        upload-files-only-if-monday: true                                                     # It sends the DEM files to the dem manager service only if it is Monday
      events:
        send-events: true                                                                     # Send the events to the dispatch event service
