server:
  port: 8086

spring:
  datasource:
    url: 'jdbc:postgresql://dbpostgres:5432/event_dispatcher'

com:
  marco:
    ixigo:
      eventdispatcher:
        notification:
          telegram:
            enabled: false