logging:
  file:
    name: ./logs/ixigo-players-manager.log
  level:
    com:
      ixigo:
        playersmanager: DEBUG

server:
  servlet:
    context-path: /playersmanager
    
com:
  ixigo:
    playersmanager:
      version: ^project.version^
