
server:
  servlet:
    context-path: /playersmanager
  port: 8080
    
com:
  marco:
    ixigo:
      playersmanager:
        version: ^project.version^

logging:
  file:
    name: ./logs/ixigo-players-manager.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        ixigo:
          playersmanager: DEBUG