logging:
  file:
    name: ./logs/ixigo-players-manager.log
  level:
    com:
      ixigo:
        playersmanager: DEBUG

server:
  servlet:
    context-path: /playersmanager
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   
    
com:
  ixigo:
    playersmanager:
      version: ^project.version^
