server:
  port: 8765
  servlet:
    context-path: /ixigodiscovery
#Every Eureka server is also a client
# So when it runs it tries to regiter
# itself to the server. These two properties
# are preventing eureka to try to register it self
# and generating errors on startup
eureka:
  server:
    renewal-percent-threshold: 0.49
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
      #hostname: ${IXIGO_EUREKA_HOST_NAME:localhost}