server:
  servlet:
    context-path: /rcon
  port: 8080
    
com:
  marco:
    ixigo:
      rconapiservice:
        version: ^project.version^

logging:
  file:
    name: ./logs/ixigo-rcon-api.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        ixigo:
          rconapiservice: DEBUG