logging:
  file:
    name: ./logs/ixigo-event-dispatcher.log
  level:
    com:
      ixigo:
        eventdispatcher: DEBUG

server:
  servlet:
    context-path: /eventsdispatcher                                                                     # Do not change this
    
com:
  ixigo:
    eventdispatcher:
      version: ^project.version^

