logging:
  file:
    name: ./logs/discordbot.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        discordbot: DEBUG

server:
  servlet:
    context-path: /discordbot
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discordbot                                                              # You can change this, but do not change the DB name.
    username: ${IXIGO_POSTGRES_USER:REPLACE_ME}
    password: ${IXIGO_POSTGRES_PASSW:REPLACE_ME}

com:
  marco:
    ixigo:
      discordbot:
        bottoken: ${DISCORD_BOT_TOKEN}
        version: ^project.version^
        services:
          discord:                                                                                                # These are the discors IDs that I use on my test server.
            serverId: 838818767219195924                                                                          # You can get these IDs from Discord,
            textChannels:                                                                                         # right click on the specific item and copy the ID
              general: 838818767219195929 
            voiceChannels:
              terrorist: 838818771136413777
              ct: 839591293545611305
              general: 838818767219195932
          rconapi:
            protocol: http                                                                                        # HTTP or HTTPs
            host: localhost                                                                                       # Host name of the Ixigo Proxy service
            port: 8763                                                                                            # Port on which the Ixigo Proxy Service is listening
            contextPath: "/ixigoproxy/ixigo-rcon-api/rcon"                                                        # Do not change this
            sendcommand: "${com.marco.ixigo.discordbot.services.rconapi.contextPath}/cmd"                         # Do not change this
            csgoServerPort: 27015                                                                                 # CSGO server port
            csgoServerHost: 192.168.1.10                                                                          # Host where the CSGO server is running
            csgoServerPassw: ${CSGO_SERVER_PASSW:localtest}                                                       # CSGO RCON password
          players-manager:
            protocol: http                                                                                        # HTTP or HTTPs
            host: localhost                                                                                       # Host name of the Ixigo Proxy service
            port: 8763                                                                                            # Port on which the Ixigo Proxy Service is listening
            contextPath: "/ixigoproxy/ixigo-players-manager/playersmanager"                                       # Do not change this
            generateTeams: "${com.marco.ixigo.discordbot.services.players-manager.contextPath}/teams"             # Do not change this
            
