logging:
  file:
    name: ./logs/ixigo-dem-manager.log
  level:
    com:
      ixigo:
        discordbot: DEBUG

server:
  servlet:
    context-path: /discordbot                                                                                           # Do not change this
com:
  ixigo:
    discordbot:
      version: ^project.version^  

spring:
    mvc:
      pathmatch:
            matching-strategy: ant_path_matcher