server:
  port: 8082

eureka:
  instance:
    prefer-ip-address : true
    ip-address : ${HOST_IP}

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:discordbot
    driverClassName: org.h2.Driver                                                              # You can change this, but do not change the DB name.
    username: sa
    password: 
    
com:
  marco:
    ixigo:
      discordbot:
        bottoken: '{cipher}9fded1a98dfd5396110d113ad5431e0612c321dc818adc6074d34ce5926d8215e7c212758f606311fcfab9c6ce31d91b0afd92ea1bba372b12dc6ae8ed366c5b8d8e6919f3d97f5b9cf39daaefc388fe'
        services:
          rconapi:
            protocol: https                                                                                        # HTTP or HTTPs
            host: '{cipher}0410d3e17fda0892ba6534b31007e1600623fe96a0fc2f625b41e2739ccac25df7f2c7dcd9084cb3f1fa3479a3873292'                                                                               # Host name of the Ixigo Proxy service
            port: 443
            csgoServerPort: 27015
            csgoServerHost: "ixigo.selfip.net"
            csgoServerPassw: '{cipher}92f488c08f3d7dc3c6696813d299ab808ec7db2e56b0202cd3efb5159b405bdf'
          players-manager:
            protocol: https                                                                                        # HTTP or HTTPs
            host: '{cipher}0410d3e17fda0892ba6534b31007e1600623fe96a0fc2f625b41e2739ccac25df7f2c7dcd9084cb3f1fa3479a3873292'                                                                               # Host name of the Ixigo Proxy service
            port: 443
