server:
  port: 8082

spring:
  datasource:
    url: 'jdbc:postgresql://dbpostgres:5432/discordbot'
    
com:
  marco:
    ixigo:
      discordbot:
        bottoken: '{cipher}9fded1a98dfd5396110d113ad5431e0612c321dc818adc6074d34ce5926d8215e7c212758f606311fcfab9c6ce31d91b0afd92ea1bba372b12dc6ae8ed366c5b8d8e6919f3d97f5b9cf39daaefc388fe'
        services:
          discord:
            serverId: 700738420686717000
            textChannels:
              general: 700738421131444234
            voiceChannels:
              terrorist: 706943323084161124
              ct: 706942842173653094
              general: 700738421131444236
          rconapi:
            host: ixigo-proxy
            csgoServerPort: 27015
            csgoServerHost: 'csgo'
            csgoServerPassw: 'test'
          players-manager:
            host: ixgo-proxy
