server:
  port: 8082

spring:
  datasource:
    url: 'jdbc:postgresql://dbpostgres:5432/discordbot'
    
com:
  marco:
    ixigo:
      discordbot:
        startBotOnStartup: true
        bottoken: '{cipher}9fded1a98dfd5396110d113ad5431e0612c321dc818adc6074d34ce5926d8215e7c212758f606311fcfab9c6ce31d91b0afd92ea1bba372b12dc6ae8ed366c5b8d8e6919f3d97f5b9cf39daaefc388fe'
        services:
          rconapi:
            host: ixigo-proxy
            csgoServerPort: 27015
            csgoServerHost: 'csgo'
            csgoServerPassw: '{cipher}10fb700c8654bb68aaabf128d525c457d6073487958add53aa6bc19f0f2aec7a'
          players-manager:
            host: ixigo-proxy
