#!/bin/bash

APP_NAME=$1
RASP_IP=$2
WORKSPACE_FOLDER=$3
BASE_FOLDER=$4

DEPLOY_APP_FOLDER=$BASE_FOLDER/$APP_NAME
SSH_ADDRESS=pi@$RASP_IP

ssh $SSH_ADDRESS mkdir -p $DEPLOY_APP_FOLDER
ssh $SSH_ADDRESS rm -rf $DEPLOY_APP_FOLDER/*
dotnet publish $WORKSPACE_FOLDER/$APP_NAME -r linux-arm64
scp -r $WORKSPACE_FOLDER/$APP_NAME/bin/Debug/netcoreapp3.1/linux-arm/* $SSH_ADDRESS:$DEPLOY_APP_FOLDER
ssh $SSH_ADDRESS chmod +x $DEPLOY_APP_FOLDER/$APP_NAME
