logging:
  file:
    name: ./logs/ixigo-ui.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        ixigo:
          ui: DEBUG

server:
  servlet:
    context-path: /cstrike
com:
  marco:
    ixigo:
      ui:
        version: ^project.version^
        urls:
          dem_manager:
            protocol: "http://"
            host: "localhost:8763"
            contextPath: "/ixigoproxy/ixigo-dem-manager/demmanger" 
            get_all_files: "${com.marco.ixigo.ui.urls.dem_manager.protocol}${com.marco.ixigo.ui.urls.dem_manager.host}${com.marco.ixigo.ui.urls.dem_manager.contextPath}/files/all"
            download_file: "${com.marco.ixigo.ui.urls.dem_manager.protocol}${com.marco.ixigo.ui.urls.dem_manager.host}${com.marco.ixigo.ui.urls.dem_manager.contextPath}/files"
            

