logging:
  file:
    name: ./logs/ixigo-rcon-api.log
  level:
    com:
      ixigo:
        ui: DEBUG

spring:
  thymeleaf:
    prefix: classpath:/static/
com:
  ixigo:
    ui:
      version: ^project.version^