logging:
  file:
    name: ./logs/ixigo-rcon-api.log
  level:
    com:
      ixigo:
        ui: DEBUG

server:
  servlet:
    context-path: /ixigoui                                                                                # Do not change this

com:
  ixigo:
    ui:
      version: ^project.version^