logging:
  file:
    name: ./logs/ixigo-ui.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        ixigo:
          ui: DEBUG

server:
  servlet:
    context-path: /cstrike
com:
  marco:
    ixigo:
      ui:
        version: ^project.version^
        urls:
          dem_parser: 
            one: "ciao"
            

