logging:
  file:
    name: ./logs/ixigo-ui.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        ixigo:
          ui: DEBUG

server:
  servlet:
    context-path: /cstrike
com:
  marco:
    ixigo:
      ui:
        version: ^project.version^
        urls:
          dem_manager:
            protocol: "http://"
            host: "localhost:8763"
            contextPath: "/ixigoproxy/ixigo-dem-manager/demmanager" 
            get_all_files: "${com.marco.ixigo.ui.urls.dem_manager.protocol}${com.marco.ixigo.ui.urls.dem_manager.host}${com.marco.ixigo.ui.urls.dem_manager.contextPath}/files/all"
            download_file: "${com.marco.ixigo.ui.urls.dem_manager.protocol}${com.marco.ixigo.ui.urls.dem_manager.host}${com.marco.ixigo.ui.urls.dem_manager.contextPath}/files"
            get_scores_types: "${com.marco.ixigo.ui.urls.dem_manager.protocol}${com.marco.ixigo.ui.urls.dem_manager.host}${com.marco.ixigo.ui.urls.dem_manager.contextPath}/demdata/scorestype"
            get_players: "${com.marco.ixigo.ui.urls.dem_manager.protocol}${com.marco.ixigo.ui.urls.dem_manager.host}${com.marco.ixigo.ui.urls.dem_manager.contextPath}/demdata/users"
          players_manager:
            protocol: "http://"
            host: "localhost:8763"
            contextPath: "/ixigoproxy/ixigo-players-manager/playersmanager"
            get_teams: "${com.marco.ixigo.ui.urls.players_manager.protocol}${com.marco.ixigo.ui.urls.players_manager.host}${com.marco.ixigo.ui.urls.players_manager.contextPath}/teams"
          rcon_api:
            protocol: "http://"
            host: "localhost:8763"
            contextPath: "/ixigoproxy/ixigo-rcon-api/rcon"
            send_cmd: "${com.marco.ixigo.ui.urls.players_manager.protocol}${com.marco.ixigo.ui.urls.players_manager.host}${com.marco.ixigo.ui.urls.players_manager.contextPath}/cmd"
            

