spring:
  security:
    user:
      name: ${IXIGO_CONFIG_SERVER_USER:REPLACE_ME}                          # User name that the springboot service has to provide in order to read the config files
      password: ${IXIGO_CONFIG_SERVER_PASSW:REPLACE_ME}                     # Password that the springboot service has to provide in order to read the config files
  application:
    name: config-service                                                    # Service name (Do not change)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcosolina/csgo_props.git                # Git repo where to get the properties from
          default-label: ${IXIGO_GIT_REPO_BRANCH:dev}
          #password: ${GIT_PASSWORD}                                        # Git user name (for private repositories)
          #username: ${GIT_USERNAME}                                        # Git password (for private repositories)
          search-paths:                                                     # List of folders that will be queried by this config service
          - '/*'
          - '/**'
          

server:
  port: 8888                                                                # Port to use when running this service
  servlet:
    context-path: /config                                                   # Application context path (Do not change)
