spring:
  security:
    user:
      name: ${IXIGO_CONFIG_SERVER_USER:REPLACE_ME}
      password: ${IXIGO_CONFIG_SERVER_PASSW:REPLACE_ME}
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/marcosolina/csgo_util.git" #Repository that hosts the properties
          default-label: ${IXIGO_GIT_REPO_BRANCH:refactoring}
          #password: ${GIT_PASSWORD}
          #username: ${GIT_USERNAME}
          search-paths: #list of folders to use when retrieving the properties
          - 'AppsProperties/**'
          

server:
  port: 8888 #Port to use when running this service
  servlet:
    context-path: /config
