server:
  port: 8081
com:
  marco:
    ixigo:
      demmanager:
        demFileManager:
          rootFolder: '/demFiles'
        notifications:
          telegram:
            enabled: true
            telegramToken: '{cipher}fb1e646375ad1db0be4506649b84738ddbda458b1c7752e40cac32a8092f48b0e2d7bffb93b40322acbaaee2bf54a155222a8bf2969591bb790eab647647b93b'
            chatGroupId: '{cipher}2d76a1fd8d99688bb90f01445e8c9df7dccccdd0b2aa336038db8082cc5a1258'
        demparser:
          environment: RASP # Enum: WINDOWS, RASP
          executionType: ASYNC # Enum: ASYNC, SYNC
          dotnetexecutable: '/demParser/DemParser'
            
spring:
  datasource:
    url: jdbc:postgresql://dbpostgres:5432/demfiles